language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
deploy:
  api_key: __GITHUB_TOKEN__
  file: app/build/outputs/apk/app-release.apk
  provider: releases
  skip_cleanup: true
on:
    repo: [REPOSITORY NAME] 
    tags: true
env:
  global:
    - NDK_VERSION=r11c
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a GITHUB_TOKEN=__GITHUB_TOKEN__

# 빌드에 사용할 스크립트입니다.
script:
    - ./build.sh

after_success:
    # Branch Merge & Push
    # 아래 예제 스크립트는 test, build가 성공적으로 되었을때 특정브랜치에
    # merge 후 push하는 예제입니다. 
    # travis_relese Branch Merge & Push
    - ./deploy.sh "$TRAVIS_BRANCH"

sudo: false
